# Generated by Django 5.2.7 on 2025-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('category', models.CharField(choices=[('DATA_ANALYSIS', 'Análise de Dados & IA'), ('EMBEDDED', 'Sistemas Embarcados & Robótica'), ('SOFTWARE_DEV', 'Desenvolvimento de Software'), ('CAD_ENGINEERING', 'Design & Engenharia (CAD)'), ('AUTOMATION', 'Automação & Scripts'), ('OTHER', 'Outro')], default='SOFTWARE_DEV', max_length=20, verbose_name='Categoria')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('technologies', models.CharField(help_text='Separar por vírgulas', max_length=200, verbose_name='Tecnologias')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Link do Projeto')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Link do GitHub')),
                ('image_url', models.URLField(help_text='Use uma URL de uma imagem hospedada (ex: Imgur)', verbose_name='URL da Imagem')),
                ('featured', models.BooleanField(default=False, verbose_name='É destaque?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['order'],
            },
        ),
    ]
